version: '3.8'
services:
  back-office-client:
    build:
      context: ./back-office-client
      dockerfile: Dockerfile
    container_name: back-office-client
    ports:
      - "3000:3000"
    volumes:
      - ./back-office-client:/app:rw
    restart: always

    