version: '3.8'
services:
  # back-office-client:
  #   build:
  #     context: ./back-office-client
  #     dockerfile: Dockerfile
  #   container_name: back-office-client-container
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./back-office-client:/app:rw
  #     - ./back-office-client/node_modules:/app/node_modules
  #   depends_on:
  #     - php
  #   networks:
  #     - symfony_network
  # ecommerce-client:
  #   build:
  #     context: ./ecommerce-client
  #     dockerfile: Dockerfile
  #   container_name: ecommerce-client-container
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./ecommerce-client:/app:rw
  #     - ./ecommerce-client/node_modules:/app/node_modules
  #   depends_on:
  #     - php
  #   networks:
  #     - symfony_network
  php:
    build:
      context: ./back-office-server
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./back-office-server:/var/www/html:cached
      - ./back-office-server/vendor:/var/www/html/vendor
      - ./back-office-server/var:/var/www/html/var
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}
    networks:
      - symfony_network

  nginx:
    build:
      context: ./back-office-server
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./back-office-server:/var/www/html
    depends_on:
      - php
    networks:
      - symfony_network

  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: izydesk-database-22
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - symfony_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: izydesk-pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - symfony_network

volumes:
  database_data:

networks:
  symfony_network:
    driver: bridge